FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy only traffic-specific files
COPY data/feature_store/traffic_for_lecture_system.csv ./data/feature_store
COPY features/traffic_predictor ./features/traffic_predictor
COPY models/traffic ./models/traffic
COPY config.py .

ENV PYTHONPATH=/app

# Hugging Face requires port 7860
CMD ["uvicorn", "features.traffic_predictor.prsntn.api:app", "--host", "0.0.0.0", "--port", "7860"]